version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: postgres_p
    environment:
      POSTGRES_USER: postgres_p
      POSTGRES_PASSWORD: password_p
      POSTGRES_DB: postgres_db_p
    volumes:
      - postgres_p:/var/lib/postgresql/data
    ports:
      - "5432:5432"
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: spring-boot-app
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres_db
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: password

volumes:
  postgres_p:
